EXTRN OUTTURE
EXTRN OUTFALSE,BUF
PUBLIC HUIWEN4
CODES SEGMENT 'C3'
HUIWEN4 PROC FAR
    MOV AL,BYTE PTR BUF[2]
    CMP AL,BYTE PTR BUF[5]
    JZ TU41
    CALL OUTFALSE
    RET
TU41: 
    MOV AL,BYTE PTR BUF[3]
    CMP AL,BYTE PTR BUF[4]
    JZ TU42
    CALL OUTFALSE
    RET
TU42: 
    CALL OUTTURE
    RET
ENDP
CODES ENDS
 