EXTRN OUTTURE
EXTRN OUTFALSE,BUF
PUBLIC HUIWEN2
CODES SEGMENT 'C3'
HUIWEN2 PROC FAR
    MOV AL,BYTE PTR BUF[2]
    CMP AL,BYTE PTR BUF[3]
    JZ TU2
    CALL OUTFALSE
    RET
TU2: CALL OUTTURE
    RET
ENDP

CODES ENDS
    