EXTRN OUTTURE
EXTRN OUTFALSE,BUF
PUBLIC HUIWEN3

CODES SEGMENT 'C3'
 
HUIWEN3 PROC FAR
    MOV AL,BYTE PTR BUF[2]
    CMP AL,BYTE PTR BUF[4]
    JZ TU3
    CALL OUTFALSE
    RET
TU3: CALL OUTTURE
    RET
ENDP
CODES ENDS
  